// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RubiconTask.Data;

#nullable disable

namespace RubiconTask.Migrations
{
    [DbContext(typeof(RubiconContext))]
    partial class RubiconContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RubiconTask.Models.Rectangle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("X1")
                        .HasColumnType("int");

                    b.Property<int>("X2")
                        .HasColumnType("int");

                    b.Property<int>("Y1")
                        .HasColumnType("int");

                    b.Property<int>("Y2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rectangles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5724),
                            IsDeleted = false,
                            X1 = 23,
                            X2 = 133,
                            Y1 = 76,
                            Y2 = 12
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5766),
                            IsDeleted = false,
                            X1 = 87,
                            X2 = 96,
                            Y1 = 95,
                            Y2 = 80
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5769),
                            IsDeleted = false,
                            X1 = 124,
                            X2 = 29,
                            Y1 = 141,
                            Y2 = 88
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5771),
                            IsDeleted = false,
                            X1 = 94,
                            X2 = 187,
                            Y1 = 183,
                            Y2 = 34
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5773),
                            IsDeleted = false,
                            X1 = 108,
                            X2 = 87,
                            Y1 = 94,
                            Y2 = 96
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5776),
                            IsDeleted = false,
                            X1 = 134,
                            X2 = 152,
                            Y1 = 50,
                            Y2 = 188
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5778),
                            IsDeleted = false,
                            X1 = 193,
                            X2 = 5,
                            Y1 = 91,
                            Y2 = 22
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5780),
                            IsDeleted = false,
                            X1 = 152,
                            X2 = 75,
                            Y1 = 90,
                            Y2 = 32
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5781),
                            IsDeleted = false,
                            X1 = 44,
                            X2 = 31,
                            Y1 = 196,
                            Y2 = 113
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5784),
                            IsDeleted = false,
                            X1 = 52,
                            X2 = 161,
                            Y1 = 94,
                            Y2 = 181
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5786),
                            IsDeleted = false,
                            X1 = 115,
                            X2 = 65,
                            Y1 = 82,
                            Y2 = 49
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5787),
                            IsDeleted = false,
                            X1 = 172,
                            X2 = 54,
                            Y1 = 129,
                            Y2 = 109
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5789),
                            IsDeleted = false,
                            X1 = 41,
                            X2 = 64,
                            Y1 = 137,
                            Y2 = 113
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5790),
                            IsDeleted = false,
                            X1 = 61,
                            X2 = 196,
                            Y1 = 57,
                            Y2 = 75
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5792),
                            IsDeleted = false,
                            X1 = 190,
                            X2 = 136,
                            Y1 = 139,
                            Y2 = 34
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5793),
                            IsDeleted = false,
                            X1 = 71,
                            X2 = 108,
                            Y1 = 4,
                            Y2 = 35
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5795),
                            IsDeleted = false,
                            X1 = 156,
                            X2 = 182,
                            Y1 = 102,
                            Y2 = 156
                        },
                        new
                        {
                            Id = 18,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5797),
                            IsDeleted = false,
                            X1 = 25,
                            X2 = 190,
                            Y1 = 67,
                            Y2 = 15
                        },
                        new
                        {
                            Id = 19,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5798),
                            IsDeleted = false,
                            X1 = 195,
                            X2 = 65,
                            Y1 = 195,
                            Y2 = 82
                        },
                        new
                        {
                            Id = 20,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5800),
                            IsDeleted = false,
                            X1 = 12,
                            X2 = 181,
                            Y1 = 108,
                            Y2 = 131
                        },
                        new
                        {
                            Id = 21,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5801),
                            IsDeleted = false,
                            X1 = 2,
                            X2 = 77,
                            Y1 = 29,
                            Y2 = 3
                        },
                        new
                        {
                            Id = 22,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5803),
                            IsDeleted = false,
                            X1 = 74,
                            X2 = 14,
                            Y1 = 26,
                            Y2 = 62
                        },
                        new
                        {
                            Id = 23,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5805),
                            IsDeleted = false,
                            X1 = 51,
                            X2 = 142,
                            Y1 = 138,
                            Y2 = 52
                        },
                        new
                        {
                            Id = 24,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5806),
                            IsDeleted = false,
                            X1 = 59,
                            X2 = 36,
                            Y1 = 109,
                            Y2 = 154
                        },
                        new
                        {
                            Id = 25,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5807),
                            IsDeleted = false,
                            X1 = 156,
                            X2 = 53,
                            Y1 = 81,
                            Y2 = 31
                        },
                        new
                        {
                            Id = 26,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5809),
                            IsDeleted = false,
                            X1 = 173,
                            X2 = 8,
                            Y1 = 170,
                            Y2 = 23
                        },
                        new
                        {
                            Id = 27,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5810),
                            IsDeleted = false,
                            X1 = 116,
                            X2 = 15,
                            Y1 = 25,
                            Y2 = 86
                        },
                        new
                        {
                            Id = 28,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5812),
                            IsDeleted = false,
                            X1 = 65,
                            X2 = 86,
                            Y1 = 56,
                            Y2 = 12
                        },
                        new
                        {
                            Id = 29,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5813),
                            IsDeleted = false,
                            X1 = 71,
                            X2 = 79,
                            Y1 = 22,
                            Y2 = 189
                        },
                        new
                        {
                            Id = 30,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5814),
                            IsDeleted = false,
                            X1 = 194,
                            X2 = 172,
                            Y1 = 58,
                            Y2 = 152
                        },
                        new
                        {
                            Id = 31,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5816),
                            IsDeleted = false,
                            X1 = 32,
                            X2 = 114,
                            Y1 = 131,
                            Y2 = 68
                        },
                        new
                        {
                            Id = 32,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5817),
                            IsDeleted = false,
                            X1 = 60,
                            X2 = 31,
                            Y1 = 177,
                            Y2 = 104
                        },
                        new
                        {
                            Id = 33,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5819),
                            IsDeleted = false,
                            X1 = 60,
                            X2 = 59,
                            Y1 = 129,
                            Y2 = 59
                        },
                        new
                        {
                            Id = 34,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5821),
                            IsDeleted = false,
                            X1 = 70,
                            X2 = 38,
                            Y1 = 134,
                            Y2 = 158
                        },
                        new
                        {
                            Id = 35,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5822),
                            IsDeleted = false,
                            X1 = 81,
                            X2 = 168,
                            Y1 = 152,
                            Y2 = 127
                        },
                        new
                        {
                            Id = 36,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5824),
                            IsDeleted = false,
                            X1 = 171,
                            X2 = 13,
                            Y1 = 3,
                            Y2 = 44
                        },
                        new
                        {
                            Id = 37,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5825),
                            IsDeleted = false,
                            X1 = 95,
                            X2 = 141,
                            Y1 = 136,
                            Y2 = 166
                        },
                        new
                        {
                            Id = 38,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5826),
                            IsDeleted = false,
                            X1 = 8,
                            X2 = 70,
                            Y1 = 118,
                            Y2 = 181
                        },
                        new
                        {
                            Id = 39,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5828),
                            IsDeleted = false,
                            X1 = 110,
                            X2 = 139,
                            Y1 = 161,
                            Y2 = 186
                        },
                        new
                        {
                            Id = 40,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5829),
                            IsDeleted = false,
                            X1 = 75,
                            X2 = 74,
                            Y1 = 132,
                            Y2 = 6
                        },
                        new
                        {
                            Id = 41,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5831),
                            IsDeleted = false,
                            X1 = 7,
                            X2 = 31,
                            Y1 = 122,
                            Y2 = 79
                        },
                        new
                        {
                            Id = 42,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5832),
                            IsDeleted = false,
                            X1 = 69,
                            X2 = 194,
                            Y1 = 178,
                            Y2 = 17
                        },
                        new
                        {
                            Id = 43,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5834),
                            IsDeleted = false,
                            X1 = 128,
                            X2 = 16,
                            Y1 = 97,
                            Y2 = 136
                        },
                        new
                        {
                            Id = 44,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5835),
                            IsDeleted = false,
                            X1 = 107,
                            X2 = 91,
                            Y1 = 116,
                            Y2 = 110
                        },
                        new
                        {
                            Id = 45,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5836),
                            IsDeleted = false,
                            X1 = 116,
                            X2 = 73,
                            Y1 = 70,
                            Y2 = 47
                        },
                        new
                        {
                            Id = 46,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5837),
                            IsDeleted = false,
                            X1 = 90,
                            X2 = 90,
                            Y1 = 97,
                            Y2 = 19
                        },
                        new
                        {
                            Id = 47,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5839),
                            IsDeleted = false,
                            X1 = 138,
                            X2 = 59,
                            Y1 = 11,
                            Y2 = 50
                        },
                        new
                        {
                            Id = 48,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5840),
                            IsDeleted = false,
                            X1 = 118,
                            X2 = 156,
                            Y1 = 89,
                            Y2 = 191
                        },
                        new
                        {
                            Id = 49,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5841),
                            IsDeleted = false,
                            X1 = 60,
                            X2 = 126,
                            Y1 = 165,
                            Y2 = 27
                        },
                        new
                        {
                            Id = 50,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5842),
                            IsDeleted = false,
                            X1 = 159,
                            X2 = 102,
                            Y1 = 43,
                            Y2 = 79
                        },
                        new
                        {
                            Id = 51,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5844),
                            IsDeleted = false,
                            X1 = 165,
                            X2 = 161,
                            Y1 = 165,
                            Y2 = 94
                        },
                        new
                        {
                            Id = 52,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5845),
                            IsDeleted = false,
                            X1 = 157,
                            X2 = 178,
                            Y1 = 45,
                            Y2 = 9
                        },
                        new
                        {
                            Id = 53,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5847),
                            IsDeleted = false,
                            X1 = 162,
                            X2 = 110,
                            Y1 = 132,
                            Y2 = 95
                        },
                        new
                        {
                            Id = 54,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5848),
                            IsDeleted = false,
                            X1 = 51,
                            X2 = 64,
                            Y1 = 110,
                            Y2 = 109
                        },
                        new
                        {
                            Id = 55,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5850),
                            IsDeleted = false,
                            X1 = 130,
                            X2 = 69,
                            Y1 = 132,
                            Y2 = 192
                        },
                        new
                        {
                            Id = 56,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5851),
                            IsDeleted = false,
                            X1 = 192,
                            X2 = 58,
                            Y1 = 52,
                            Y2 = 187
                        },
                        new
                        {
                            Id = 57,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5852),
                            IsDeleted = false,
                            X1 = 101,
                            X2 = 106,
                            Y1 = 21,
                            Y2 = 19
                        },
                        new
                        {
                            Id = 58,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5853),
                            IsDeleted = false,
                            X1 = 11,
                            X2 = 21,
                            Y1 = 15,
                            Y2 = 51
                        },
                        new
                        {
                            Id = 59,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5855),
                            IsDeleted = false,
                            X1 = 64,
                            X2 = 13,
                            Y1 = 129,
                            Y2 = 171
                        },
                        new
                        {
                            Id = 60,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5856),
                            IsDeleted = false,
                            X1 = 17,
                            X2 = 114,
                            Y1 = 20,
                            Y2 = 155
                        },
                        new
                        {
                            Id = 61,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5857),
                            IsDeleted = false,
                            X1 = 170,
                            X2 = 143,
                            Y1 = 162,
                            Y2 = 7
                        },
                        new
                        {
                            Id = 62,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5858),
                            IsDeleted = false,
                            X1 = 17,
                            X2 = 111,
                            Y1 = 189,
                            Y2 = 85
                        },
                        new
                        {
                            Id = 63,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5860),
                            IsDeleted = false,
                            X1 = 63,
                            X2 = 97,
                            Y1 = 78,
                            Y2 = 15
                        },
                        new
                        {
                            Id = 64,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5861),
                            IsDeleted = false,
                            X1 = 31,
                            X2 = 120,
                            Y1 = 137,
                            Y2 = 119
                        },
                        new
                        {
                            Id = 65,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5863),
                            IsDeleted = false,
                            X1 = 37,
                            X2 = 46,
                            Y1 = 41,
                            Y2 = 159
                        },
                        new
                        {
                            Id = 66,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5865),
                            IsDeleted = false,
                            X1 = 3,
                            X2 = 125,
                            Y1 = 159,
                            Y2 = 78
                        },
                        new
                        {
                            Id = 67,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5867),
                            IsDeleted = false,
                            X1 = 127,
                            X2 = 133,
                            Y1 = 117,
                            Y2 = 26
                        },
                        new
                        {
                            Id = 68,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5868),
                            IsDeleted = false,
                            X1 = 28,
                            X2 = 2,
                            Y1 = 63,
                            Y2 = 92
                        },
                        new
                        {
                            Id = 69,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5870),
                            IsDeleted = false,
                            X1 = 111,
                            X2 = 0,
                            Y1 = 72,
                            Y2 = 196
                        },
                        new
                        {
                            Id = 70,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5871),
                            IsDeleted = false,
                            X1 = 193,
                            X2 = 77,
                            Y1 = 56,
                            Y2 = 132
                        },
                        new
                        {
                            Id = 71,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5873),
                            IsDeleted = false,
                            X1 = 106,
                            X2 = 2,
                            Y1 = 38,
                            Y2 = 123
                        },
                        new
                        {
                            Id = 72,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5874),
                            IsDeleted = false,
                            X1 = 169,
                            X2 = 135,
                            Y1 = 8,
                            Y2 = 55
                        },
                        new
                        {
                            Id = 73,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5875),
                            IsDeleted = false,
                            X1 = 127,
                            X2 = 154,
                            Y1 = 103,
                            Y2 = 170
                        },
                        new
                        {
                            Id = 74,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5877),
                            IsDeleted = false,
                            X1 = 71,
                            X2 = 51,
                            Y1 = 96,
                            Y2 = 96
                        },
                        new
                        {
                            Id = 75,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5878),
                            IsDeleted = false,
                            X1 = 16,
                            X2 = 144,
                            Y1 = 180,
                            Y2 = 199
                        },
                        new
                        {
                            Id = 76,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5879),
                            IsDeleted = false,
                            X1 = 10,
                            X2 = 21,
                            Y1 = 138,
                            Y2 = 81
                        },
                        new
                        {
                            Id = 77,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5881),
                            IsDeleted = false,
                            X1 = 55,
                            X2 = 127,
                            Y1 = 99,
                            Y2 = 51
                        },
                        new
                        {
                            Id = 78,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5882),
                            IsDeleted = false,
                            X1 = 47,
                            X2 = 53,
                            Y1 = 72,
                            Y2 = 121
                        },
                        new
                        {
                            Id = 79,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5883),
                            IsDeleted = false,
                            X1 = 4,
                            X2 = 59,
                            Y1 = 101,
                            Y2 = 144
                        },
                        new
                        {
                            Id = 80,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5885),
                            IsDeleted = false,
                            X1 = 44,
                            X2 = 79,
                            Y1 = 3,
                            Y2 = 43
                        },
                        new
                        {
                            Id = 81,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5886),
                            IsDeleted = false,
                            X1 = 54,
                            X2 = 70,
                            Y1 = 189,
                            Y2 = 193
                        },
                        new
                        {
                            Id = 82,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5887),
                            IsDeleted = false,
                            X1 = 144,
                            X2 = 10,
                            Y1 = 63,
                            Y2 = 76
                        },
                        new
                        {
                            Id = 83,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5889),
                            IsDeleted = false,
                            X1 = 65,
                            X2 = 88,
                            Y1 = 108,
                            Y2 = 191
                        },
                        new
                        {
                            Id = 84,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5890),
                            IsDeleted = false,
                            X1 = 172,
                            X2 = 103,
                            Y1 = 195,
                            Y2 = 5
                        },
                        new
                        {
                            Id = 85,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5892),
                            IsDeleted = false,
                            X1 = 153,
                            X2 = 14,
                            Y1 = 47,
                            Y2 = 107
                        },
                        new
                        {
                            Id = 86,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5893),
                            IsDeleted = false,
                            X1 = 179,
                            X2 = 76,
                            Y1 = 170,
                            Y2 = 1
                        },
                        new
                        {
                            Id = 87,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5894),
                            IsDeleted = false,
                            X1 = 72,
                            X2 = 161,
                            Y1 = 51,
                            Y2 = 22
                        },
                        new
                        {
                            Id = 88,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5896),
                            IsDeleted = false,
                            X1 = 74,
                            X2 = 149,
                            Y1 = 84,
                            Y2 = 197
                        },
                        new
                        {
                            Id = 89,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5897),
                            IsDeleted = false,
                            X1 = 119,
                            X2 = 161,
                            Y1 = 80,
                            Y2 = 170
                        },
                        new
                        {
                            Id = 90,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5899),
                            IsDeleted = false,
                            X1 = 40,
                            X2 = 31,
                            Y1 = 61,
                            Y2 = 24
                        },
                        new
                        {
                            Id = 91,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5900),
                            IsDeleted = false,
                            X1 = 49,
                            X2 = 154,
                            Y1 = 14,
                            Y2 = 47
                        },
                        new
                        {
                            Id = 92,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5902),
                            IsDeleted = false,
                            X1 = 45,
                            X2 = 137,
                            Y1 = 80,
                            Y2 = 172
                        },
                        new
                        {
                            Id = 93,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5903),
                            IsDeleted = false,
                            X1 = 187,
                            X2 = 104,
                            Y1 = 87,
                            Y2 = 20
                        },
                        new
                        {
                            Id = 94,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5904),
                            IsDeleted = false,
                            X1 = 65,
                            X2 = 83,
                            Y1 = 75,
                            Y2 = 23
                        },
                        new
                        {
                            Id = 95,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5905),
                            IsDeleted = false,
                            X1 = 137,
                            X2 = 197,
                            Y1 = 127,
                            Y2 = 0
                        },
                        new
                        {
                            Id = 96,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5907),
                            IsDeleted = false,
                            X1 = 176,
                            X2 = 7,
                            Y1 = 38,
                            Y2 = 111
                        },
                        new
                        {
                            Id = 97,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5908),
                            IsDeleted = false,
                            X1 = 185,
                            X2 = 55,
                            Y1 = 40,
                            Y2 = 91
                        },
                        new
                        {
                            Id = 98,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5910),
                            IsDeleted = false,
                            X1 = 105,
                            X2 = 7,
                            Y1 = 116,
                            Y2 = 41
                        },
                        new
                        {
                            Id = 99,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5911),
                            IsDeleted = false,
                            X1 = 40,
                            X2 = 55,
                            Y1 = 150,
                            Y2 = 11
                        },
                        new
                        {
                            Id = 100,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5913),
                            IsDeleted = false,
                            X1 = 69,
                            X2 = 92,
                            Y1 = 118,
                            Y2 = 109
                        },
                        new
                        {
                            Id = 101,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5914),
                            IsDeleted = false,
                            X1 = 62,
                            X2 = 172,
                            Y1 = 117,
                            Y2 = 168
                        },
                        new
                        {
                            Id = 102,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5915),
                            IsDeleted = false,
                            X1 = 83,
                            X2 = 132,
                            Y1 = 48,
                            Y2 = 82
                        },
                        new
                        {
                            Id = 103,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5917),
                            IsDeleted = false,
                            X1 = 197,
                            X2 = 84,
                            Y1 = 12,
                            Y2 = 44
                        },
                        new
                        {
                            Id = 104,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5918),
                            IsDeleted = false,
                            X1 = 141,
                            X2 = 151,
                            Y1 = 139,
                            Y2 = 66
                        },
                        new
                        {
                            Id = 105,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5919),
                            IsDeleted = false,
                            X1 = 6,
                            X2 = 149,
                            Y1 = 145,
                            Y2 = 45
                        },
                        new
                        {
                            Id = 106,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5921),
                            IsDeleted = false,
                            X1 = 94,
                            X2 = 74,
                            Y1 = 89,
                            Y2 = 79
                        },
                        new
                        {
                            Id = 107,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5949),
                            IsDeleted = false,
                            X1 = 133,
                            X2 = 194,
                            Y1 = 111,
                            Y2 = 70
                        },
                        new
                        {
                            Id = 108,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5951),
                            IsDeleted = false,
                            X1 = 70,
                            X2 = 190,
                            Y1 = 132,
                            Y2 = 69
                        },
                        new
                        {
                            Id = 109,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5953),
                            IsDeleted = false,
                            X1 = 184,
                            X2 = 70,
                            Y1 = 90,
                            Y2 = 134
                        },
                        new
                        {
                            Id = 110,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5954),
                            IsDeleted = false,
                            X1 = 28,
                            X2 = 56,
                            Y1 = 68,
                            Y2 = 120
                        },
                        new
                        {
                            Id = 111,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5956),
                            IsDeleted = false,
                            X1 = 86,
                            X2 = 131,
                            Y1 = 72,
                            Y2 = 3
                        },
                        new
                        {
                            Id = 112,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5958),
                            IsDeleted = false,
                            X1 = 184,
                            X2 = 21,
                            Y1 = 71,
                            Y2 = 58
                        },
                        new
                        {
                            Id = 113,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5959),
                            IsDeleted = false,
                            X1 = 142,
                            X2 = 6,
                            Y1 = 151,
                            Y2 = 15
                        },
                        new
                        {
                            Id = 114,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5960),
                            IsDeleted = false,
                            X1 = 118,
                            X2 = 166,
                            Y1 = 91,
                            Y2 = 1
                        },
                        new
                        {
                            Id = 115,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5962),
                            IsDeleted = false,
                            X1 = 92,
                            X2 = 30,
                            Y1 = 17,
                            Y2 = 30
                        },
                        new
                        {
                            Id = 116,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5963),
                            IsDeleted = false,
                            X1 = 48,
                            X2 = 86,
                            Y1 = 115,
                            Y2 = 22
                        },
                        new
                        {
                            Id = 117,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5965),
                            IsDeleted = false,
                            X1 = 91,
                            X2 = 150,
                            Y1 = 51,
                            Y2 = 152
                        },
                        new
                        {
                            Id = 118,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5966),
                            IsDeleted = false,
                            X1 = 23,
                            X2 = 170,
                            Y1 = 173,
                            Y2 = 120
                        },
                        new
                        {
                            Id = 119,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5967),
                            IsDeleted = false,
                            X1 = 46,
                            X2 = 185,
                            Y1 = 86,
                            Y2 = 161
                        },
                        new
                        {
                            Id = 120,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5969),
                            IsDeleted = false,
                            X1 = 195,
                            X2 = 95,
                            Y1 = 73,
                            Y2 = 91
                        },
                        new
                        {
                            Id = 121,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5970),
                            IsDeleted = false,
                            X1 = 38,
                            X2 = 88,
                            Y1 = 146,
                            Y2 = 68
                        },
                        new
                        {
                            Id = 122,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5972),
                            IsDeleted = false,
                            X1 = 126,
                            X2 = 94,
                            Y1 = 66,
                            Y2 = 143
                        },
                        new
                        {
                            Id = 123,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5973),
                            IsDeleted = false,
                            X1 = 59,
                            X2 = 89,
                            Y1 = 85,
                            Y2 = 151
                        },
                        new
                        {
                            Id = 124,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5975),
                            IsDeleted = false,
                            X1 = 174,
                            X2 = 45,
                            Y1 = 195,
                            Y2 = 17
                        },
                        new
                        {
                            Id = 125,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5976),
                            IsDeleted = false,
                            X1 = 39,
                            X2 = 145,
                            Y1 = 121,
                            Y2 = 152
                        },
                        new
                        {
                            Id = 126,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5977),
                            IsDeleted = false,
                            X1 = 33,
                            X2 = 196,
                            Y1 = 188,
                            Y2 = 81
                        },
                        new
                        {
                            Id = 127,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5978),
                            IsDeleted = false,
                            X1 = 0,
                            X2 = 25,
                            Y1 = 176,
                            Y2 = 142
                        },
                        new
                        {
                            Id = 128,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5980),
                            IsDeleted = false,
                            X1 = 154,
                            X2 = 95,
                            Y1 = 141,
                            Y2 = 165
                        },
                        new
                        {
                            Id = 129,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5981),
                            IsDeleted = false,
                            X1 = 50,
                            X2 = 81,
                            Y1 = 108,
                            Y2 = 97
                        },
                        new
                        {
                            Id = 130,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5984),
                            IsDeleted = false,
                            X1 = 48,
                            X2 = 42,
                            Y1 = 137,
                            Y2 = 162
                        },
                        new
                        {
                            Id = 131,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5986),
                            IsDeleted = false,
                            X1 = 152,
                            X2 = 28,
                            Y1 = 130,
                            Y2 = 8
                        },
                        new
                        {
                            Id = 132,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5987),
                            IsDeleted = false,
                            X1 = 106,
                            X2 = 192,
                            Y1 = 112,
                            Y2 = 197
                        },
                        new
                        {
                            Id = 133,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5989),
                            IsDeleted = false,
                            X1 = 44,
                            X2 = 161,
                            Y1 = 65,
                            Y2 = 41
                        },
                        new
                        {
                            Id = 134,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5990),
                            IsDeleted = false,
                            X1 = 55,
                            X2 = 139,
                            Y1 = 31,
                            Y2 = 31
                        },
                        new
                        {
                            Id = 135,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5992),
                            IsDeleted = false,
                            X1 = 57,
                            X2 = 39,
                            Y1 = 99,
                            Y2 = 82
                        },
                        new
                        {
                            Id = 136,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5993),
                            IsDeleted = false,
                            X1 = 110,
                            X2 = 92,
                            Y1 = 121,
                            Y2 = 146
                        },
                        new
                        {
                            Id = 137,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5995),
                            IsDeleted = false,
                            X1 = 33,
                            X2 = 19,
                            Y1 = 4,
                            Y2 = 130
                        },
                        new
                        {
                            Id = 138,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5996),
                            IsDeleted = false,
                            X1 = 115,
                            X2 = 108,
                            Y1 = 107,
                            Y2 = 190
                        },
                        new
                        {
                            Id = 139,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(5998),
                            IsDeleted = false,
                            X1 = 198,
                            X2 = 144,
                            Y1 = 175,
                            Y2 = 34
                        },
                        new
                        {
                            Id = 140,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6000),
                            IsDeleted = false,
                            X1 = 132,
                            X2 = 88,
                            Y1 = 158,
                            Y2 = 27
                        },
                        new
                        {
                            Id = 141,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6001),
                            IsDeleted = false,
                            X1 = 186,
                            X2 = 157,
                            Y1 = 73,
                            Y2 = 16
                        },
                        new
                        {
                            Id = 142,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6003),
                            IsDeleted = false,
                            X1 = 194,
                            X2 = 60,
                            Y1 = 143,
                            Y2 = 24
                        },
                        new
                        {
                            Id = 143,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6005),
                            IsDeleted = false,
                            X1 = 95,
                            X2 = 103,
                            Y1 = 174,
                            Y2 = 192
                        },
                        new
                        {
                            Id = 144,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6006),
                            IsDeleted = false,
                            X1 = 27,
                            X2 = 115,
                            Y1 = 75,
                            Y2 = 135
                        },
                        new
                        {
                            Id = 145,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6008),
                            IsDeleted = false,
                            X1 = 45,
                            X2 = 118,
                            Y1 = 20,
                            Y2 = 74
                        },
                        new
                        {
                            Id = 146,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6009),
                            IsDeleted = false,
                            X1 = 66,
                            X2 = 45,
                            Y1 = 6,
                            Y2 = 68
                        },
                        new
                        {
                            Id = 147,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6011),
                            IsDeleted = false,
                            X1 = 175,
                            X2 = 131,
                            Y1 = 143,
                            Y2 = 141
                        },
                        new
                        {
                            Id = 148,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6012),
                            IsDeleted = false,
                            X1 = 39,
                            X2 = 155,
                            Y1 = 101,
                            Y2 = 110
                        },
                        new
                        {
                            Id = 149,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6013),
                            IsDeleted = false,
                            X1 = 69,
                            X2 = 192,
                            Y1 = 178,
                            Y2 = 144
                        },
                        new
                        {
                            Id = 150,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6015),
                            IsDeleted = false,
                            X1 = 23,
                            X2 = 131,
                            Y1 = 192,
                            Y2 = 41
                        },
                        new
                        {
                            Id = 151,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6016),
                            IsDeleted = false,
                            X1 = 178,
                            X2 = 68,
                            Y1 = 30,
                            Y2 = 22
                        },
                        new
                        {
                            Id = 152,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6018),
                            IsDeleted = false,
                            X1 = 84,
                            X2 = 157,
                            Y1 = 61,
                            Y2 = 177
                        },
                        new
                        {
                            Id = 153,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6019),
                            IsDeleted = false,
                            X1 = 58,
                            X2 = 186,
                            Y1 = 0,
                            Y2 = 146
                        },
                        new
                        {
                            Id = 154,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6020),
                            IsDeleted = false,
                            X1 = 119,
                            X2 = 172,
                            Y1 = 162,
                            Y2 = 104
                        },
                        new
                        {
                            Id = 155,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6021),
                            IsDeleted = false,
                            X1 = 122,
                            X2 = 151,
                            Y1 = 44,
                            Y2 = 78
                        },
                        new
                        {
                            Id = 156,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6023),
                            IsDeleted = false,
                            X1 = 23,
                            X2 = 162,
                            Y1 = 57,
                            Y2 = 23
                        },
                        new
                        {
                            Id = 157,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6024),
                            IsDeleted = false,
                            X1 = 155,
                            X2 = 27,
                            Y1 = 66,
                            Y2 = 151
                        },
                        new
                        {
                            Id = 158,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6025),
                            IsDeleted = false,
                            X1 = 131,
                            X2 = 2,
                            Y1 = 39,
                            Y2 = 102
                        },
                        new
                        {
                            Id = 159,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6027),
                            IsDeleted = false,
                            X1 = 123,
                            X2 = 147,
                            Y1 = 111,
                            Y2 = 165
                        },
                        new
                        {
                            Id = 160,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6028),
                            IsDeleted = false,
                            X1 = 80,
                            X2 = 136,
                            Y1 = 103,
                            Y2 = 58
                        },
                        new
                        {
                            Id = 161,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6030),
                            IsDeleted = false,
                            X1 = 195,
                            X2 = 109,
                            Y1 = 101,
                            Y2 = 157
                        },
                        new
                        {
                            Id = 162,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6031),
                            IsDeleted = false,
                            X1 = 156,
                            X2 = 118,
                            Y1 = 186,
                            Y2 = 150
                        },
                        new
                        {
                            Id = 163,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6032),
                            IsDeleted = false,
                            X1 = 49,
                            X2 = 103,
                            Y1 = 64,
                            Y2 = 151
                        },
                        new
                        {
                            Id = 164,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6034),
                            IsDeleted = false,
                            X1 = 53,
                            X2 = 26,
                            Y1 = 123,
                            Y2 = 57
                        },
                        new
                        {
                            Id = 165,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6035),
                            IsDeleted = false,
                            X1 = 46,
                            X2 = 36,
                            Y1 = 54,
                            Y2 = 172
                        },
                        new
                        {
                            Id = 166,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6036),
                            IsDeleted = false,
                            X1 = 199,
                            X2 = 117,
                            Y1 = 181,
                            Y2 = 125
                        },
                        new
                        {
                            Id = 167,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6038),
                            IsDeleted = false,
                            X1 = 181,
                            X2 = 18,
                            Y1 = 59,
                            Y2 = 73
                        },
                        new
                        {
                            Id = 168,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6039),
                            IsDeleted = false,
                            X1 = 28,
                            X2 = 157,
                            Y1 = 47,
                            Y2 = 168
                        },
                        new
                        {
                            Id = 169,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6041),
                            IsDeleted = false,
                            X1 = 131,
                            X2 = 133,
                            Y1 = 61,
                            Y2 = 167
                        },
                        new
                        {
                            Id = 170,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6042),
                            IsDeleted = false,
                            X1 = 5,
                            X2 = 31,
                            Y1 = 164,
                            Y2 = 76
                        },
                        new
                        {
                            Id = 171,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6044),
                            IsDeleted = false,
                            X1 = 143,
                            X2 = 42,
                            Y1 = 174,
                            Y2 = 75
                        },
                        new
                        {
                            Id = 172,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6045),
                            IsDeleted = false,
                            X1 = 199,
                            X2 = 195,
                            Y1 = 5,
                            Y2 = 56
                        },
                        new
                        {
                            Id = 173,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6047),
                            IsDeleted = false,
                            X1 = 126,
                            X2 = 9,
                            Y1 = 54,
                            Y2 = 18
                        },
                        new
                        {
                            Id = 174,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6048),
                            IsDeleted = false,
                            X1 = 56,
                            X2 = 1,
                            Y1 = 1,
                            Y2 = 117
                        },
                        new
                        {
                            Id = 175,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6049),
                            IsDeleted = false,
                            X1 = 51,
                            X2 = 61,
                            Y1 = 82,
                            Y2 = 55
                        },
                        new
                        {
                            Id = 176,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6051),
                            IsDeleted = false,
                            X1 = 11,
                            X2 = 80,
                            Y1 = 60,
                            Y2 = 83
                        },
                        new
                        {
                            Id = 177,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6052),
                            IsDeleted = false,
                            X1 = 144,
                            X2 = 124,
                            Y1 = 85,
                            Y2 = 68
                        },
                        new
                        {
                            Id = 178,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6054),
                            IsDeleted = false,
                            X1 = 85,
                            X2 = 78,
                            Y1 = 29,
                            Y2 = 119
                        },
                        new
                        {
                            Id = 179,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6055),
                            IsDeleted = false,
                            X1 = 29,
                            X2 = 4,
                            Y1 = 43,
                            Y2 = 190
                        },
                        new
                        {
                            Id = 180,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6056),
                            IsDeleted = false,
                            X1 = 2,
                            X2 = 100,
                            Y1 = 34,
                            Y2 = 59
                        },
                        new
                        {
                            Id = 181,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6058),
                            IsDeleted = false,
                            X1 = 10,
                            X2 = 151,
                            Y1 = 26,
                            Y2 = 149
                        },
                        new
                        {
                            Id = 182,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6059),
                            IsDeleted = false,
                            X1 = 93,
                            X2 = 66,
                            Y1 = 122,
                            Y2 = 42
                        },
                        new
                        {
                            Id = 183,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6060),
                            IsDeleted = false,
                            X1 = 11,
                            X2 = 90,
                            Y1 = 94,
                            Y2 = 115
                        },
                        new
                        {
                            Id = 184,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6062),
                            IsDeleted = false,
                            X1 = 43,
                            X2 = 43,
                            Y1 = 54,
                            Y2 = 164
                        },
                        new
                        {
                            Id = 185,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6063),
                            IsDeleted = false,
                            X1 = 181,
                            X2 = 123,
                            Y1 = 143,
                            Y2 = 105
                        },
                        new
                        {
                            Id = 186,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6065),
                            IsDeleted = false,
                            X1 = 148,
                            X2 = 98,
                            Y1 = 2,
                            Y2 = 1
                        },
                        new
                        {
                            Id = 187,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6067),
                            IsDeleted = false,
                            X1 = 22,
                            X2 = 139,
                            Y1 = 12,
                            Y2 = 172
                        },
                        new
                        {
                            Id = 188,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6068),
                            IsDeleted = false,
                            X1 = 115,
                            X2 = 5,
                            Y1 = 110,
                            Y2 = 148
                        },
                        new
                        {
                            Id = 189,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6070),
                            IsDeleted = false,
                            X1 = 78,
                            X2 = 172,
                            Y1 = 6,
                            Y2 = 74
                        },
                        new
                        {
                            Id = 190,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6071),
                            IsDeleted = false,
                            X1 = 9,
                            X2 = 178,
                            Y1 = 98,
                            Y2 = 149
                        },
                        new
                        {
                            Id = 191,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6073),
                            IsDeleted = false,
                            X1 = 72,
                            X2 = 8,
                            Y1 = 158,
                            Y2 = 140
                        },
                        new
                        {
                            Id = 192,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6074),
                            IsDeleted = false,
                            X1 = 16,
                            X2 = 147,
                            Y1 = 65,
                            Y2 = 59
                        },
                        new
                        {
                            Id = 193,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6075),
                            IsDeleted = false,
                            X1 = 95,
                            X2 = 171,
                            Y1 = 67,
                            Y2 = 139
                        },
                        new
                        {
                            Id = 194,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6076),
                            IsDeleted = false,
                            X1 = 149,
                            X2 = 181,
                            Y1 = 164,
                            Y2 = 157
                        },
                        new
                        {
                            Id = 195,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6078),
                            IsDeleted = false,
                            X1 = 35,
                            X2 = 104,
                            Y1 = 187,
                            Y2 = 107
                        },
                        new
                        {
                            Id = 196,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6079),
                            IsDeleted = false,
                            X1 = 2,
                            X2 = 65,
                            Y1 = 27,
                            Y2 = 169
                        },
                        new
                        {
                            Id = 197,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6081),
                            IsDeleted = false,
                            X1 = 134,
                            X2 = 118,
                            Y1 = 143,
                            Y2 = 134
                        },
                        new
                        {
                            Id = 198,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6082),
                            IsDeleted = false,
                            X1 = 157,
                            X2 = 112,
                            Y1 = 160,
                            Y2 = 99
                        },
                        new
                        {
                            Id = 199,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6083),
                            IsDeleted = false,
                            X1 = 185,
                            X2 = 129,
                            Y1 = 80,
                            Y2 = 95
                        },
                        new
                        {
                            Id = 200,
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6085),
                            IsDeleted = false,
                            X1 = 191,
                            X2 = 11,
                            Y1 = 129,
                            Y2 = 60
                        });
                });

            modelBuilder.Entity("RubiconTask.Models.RubiconUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RubiconUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "92710ff8-e4bf-4f13-be1a-7bbba8942f9f",
                            CreatedOn = new DateTime(2023, 11, 14, 16, 6, 36, 840, DateTimeKind.Local).AddTicks(6182),
                            Email = "testuser@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEG5bLNoX/YE3cZtzWe2WKhlKw+LirHh92hVG4Nk8+KrSd+op0LhDhfUpoSdpexZnSw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "902c6a5a-0e75-4d5b-85a8-a1c24308e2e4",
                            TwoFactorEnabled = false,
                            UserName = "testuser@gmail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
